name: project_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  google_sign_in: ^6.2.2
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  emoji_picker_flutter: ^4.2.0
  firebase_messaging: ^15.2.0
#  flutter_facebook_auth: '^3.5.0'
  http: ^1.2.2
  googleapis_auth: ^1.6.0
  flutter_notification_channel: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "images/icon.png"
  min_sdk_android: 24
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_forceground: "images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - images/
