// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdT_hnhY4b49q-N1_tSqTG4nn4rhbEes8',
    appId: '1:731507380272:web:aaad9c06c91d2fb91c9df5',
    messagingSenderId: '731507380272',
    projectId: 'chat-ab619',
    authDomain: 'chat-ab619.firebaseapp.com',
    storageBucket: 'chat-ab619.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkPuotQbyAX9fZ-DLGw3q8tfRCw-4Q_vw',
    appId: '1:731507380272:android:d0dc448a89c952051c9df5',
    messagingSenderId: '731507380272',
    projectId: 'chat-ab619',
    storageBucket: 'chat-ab619.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLa0TDOlZQIwZ1uwnLMoxR6ZaDS0gVNuE',
    appId: '1:731507380272:ios:25b5c4d7c45a854c1c9df5',
    messagingSenderId: '731507380272',
    projectId: 'chat-ab619',
    storageBucket: 'chat-ab619.firebasestorage.app',
    androidClientId: '731507380272-phir41up5l82qqegu0skr0cuvnmaf4v2.apps.googleusercontent.com',
    iosClientId: '731507380272-7adssrbciarvnjef8f8605qjopcnd6r3.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLa0TDOlZQIwZ1uwnLMoxR6ZaDS0gVNuE',
    appId: '1:731507380272:ios:25b5c4d7c45a854c1c9df5',
    messagingSenderId: '731507380272',
    projectId: 'chat-ab619',
    storageBucket: 'chat-ab619.firebasestorage.app',
    iosBundleId: 'com.example.projectMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdT_hnhY4b49q-N1_tSqTG4nn4rhbEes8',
    appId: '1:731507380272:web:d6bb858b665203511c9df5',
    messagingSenderId: '731507380272',
    projectId: 'chat-ab619',
    authDomain: 'chat-ab619.firebaseapp.com',
    storageBucket: 'chat-ab619.firebasestorage.app',
  );
}